### ISSUE TITLE
Reusing a mapper with step definitions doesn't apply steps

### ISSUE THREAD

**Issue by c0** [rom-rb/rom-mapper#13]
When reusing a mapper (e.g. `mapper: FooMapper`) that has step definitions, the steps are not applied. Below is a failing spec I places in the [integration specs](https://github.com/rom-rb/rom/blob/master/spec/integration/mappers/reusing_mappers_spec.rb)

``` ruby

it 'allows using another mapper with steps in an embbedded hash' do
  class Test::PriorityMapper < ROM::Mapper
    step do
      attribute :value, type: :integer
    end

    step do
      attribute :desc
    end
  end

  class Test::TaskMapper < ROM::Mapper
    attribute :title
    embedded :priority, type: :hash, mapper: Test::PriorityMapper
  end

  mapper = Test::TaskMapper.build
  relation = [{ title: 'Task One', priority: { value: '1' } }, { title: 'Task Two', priority: { value: '2' } }]
  result = mapper.call(relation)

  expect(result).to eql([
    { title: 'Task One', priority: { value: 1 } },
    { title: 'Task Two', priority: { value: 2 } }
  ])
end
```

```
Failures:

  1) Reusing mappers allows using another mapper with steps in an embbedded hash
     Failure/Error: expect(result).to eql([

       expected: [{:title=>"Task One", :priority=>{:value=>1}}, {:title=>"Task Two", :priority=>{:value=>2}}]
            got: [{:title=>"Task One", :priority=>{:value=>"1"}}, {:title=>"Task Two", :priority=>{:value=>"2"}}]

       (compared using eql?)

       Diff:
       @@ -1,3 +1,3 @@
       -[{:title=>"Task One", :priority=>{:value=>1}},
       - {:title=>"Task Two", :priority=>{:value=>2}}]
       +[{:title=>"Task One", :priority=>{:value=>"1"}},
       + {:title=>"Task Two", :priority=>{:value=>"2"}}]

     # ./spec/integration/mappers/reusing_mappers_spec.rb:64:in `block (2 levels) in <top (required)>'
     # ./spec/support/constant_leak_finder.rb:6:in `find'
     # ./spec/spec_helper.rb:46:in `block (2 levels) in <top (required)>'
```

**Comment by solnic** [comment]
Closing as this DSL will be deprecated
