### ISSUE TITLE
decimal conversion fails with NoMethodError if missing input

### ISSUE THREAD

**Issue by joevandyk** [rom-rb/rom-mapper#33]
```
$ cat t.rb
require 'rom-mapper'

class Product < ROM::Mapper
  symbolize_keys true
  reject_keys true

  attribute :cost, type: :decimal
end


Product.build.call([{}])


$ ruby t.rb
/usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/coercions.rb:107:in `to_decimal': undefined method `to_d' for nil:NilClass (NoMethodError)
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/hash.rb:270:in `map_value'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/composite.rb:30:in `call'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/array.rb:50:in `block in map_array!'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/array.rb:50:in `map!'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/array.rb:50:in `map_array!'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/array.rb:41:in `map_array'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/rom-mapper-0.3.0/lib/rom/mapper.rb:93:in `block in call'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/rom-mapper-0.3.0/lib/rom/mapper.rb:93:in `each'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/rom-mapper-0.3.0/lib/rom/mapper.rb:93:in `reduce'
    from /usr/local/tanga/ruby-2.2.4/lib/ruby/gems/2.2.0/gems/rom-mapper-0.3.0/lib/rom/mapper.rb:93:in `call'
    from t.rb:11:in `<main>'
```

is that expected behavior? Seems like if there's a failure creating the object, a different error type should be raised.

**Comment by solnic** [comment]
Closing as this DSL will be deprecated
