### ISSUE TITLE
Unwrap for optional key in hash

### ISSUE THREAD

**Issue by Fattaf** [rom-rb/rom-mapper#38]
Hi guys. I have a problem. I am trying to map my hash with nested optional hash using `unwrap` method.

```
unwrap :quote do
  attribute :quote_id, from: :id
end
```
 And when it's not set, I have an error. 

<details>

```
ArgumentError:
       odd number of arguments for Hash
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/hash.rb:246:in `[]'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/hash.rb:246:in `accept_keys'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/composite.rb:30:in `call'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/hash.rb:270:in `map_value'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/composite.rb:30:in `call'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/composite.rb:30:in `call'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/array.rb:50:in `block in map_array!'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/array.rb:50:in `map!'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/array.rb:50:in `map_array!'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/array.rb:41:in `map_array'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/transproc-0.4.0/lib/transproc/function.rb:47:in `call'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/rom-mapper-0.4.0/lib/rom/mapper.rb:93:in `block in call'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/rom-mapper-0.4.0/lib/rom/mapper.rb:93:in `each'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/rom-mapper-0.4.0/lib/rom/mapper.rb:93:in `reduce'
     # /Users/fattaf/.rvm/gems/ruby-2.3.0@matic-www/gems/rom-mapper-0.4.0/lib/rom/mapper.rb:93:in `call'
```
</details>

**Comment by Kukunin** [comment]
It affects me as well. One more detail, that it gives such error only if `reject_keys true` is used.

Without it gives another exception
<details>

```
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/hash.rb:270:in `map_value'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/function.rb:47:in `call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/function.rb:47:in `call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/hash.rb:270:in `map_value'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/function.rb:47:in `call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/function.rb:47:in `call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/composite.rb:30:in `call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/array.rb:50:in `block in map_array!'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/array.rb:50:in `map!'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/array.rb:50:in `map_array!'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/array.rb:41:in `map_array'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/function.rb:47:in `call'
     # /Users/kukunin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/transproc-0.4.1/lib/transproc/function.rb:47:in `call'
```
</details>

**Comment by Kukunin** [comment]
actually, I investigated this issue, and found out, that it's better to use

```ruby
attribute :quote_id, from: :quote, &->(value) { value&.[](:id) }
```

without `unwrap`, despite syntax is creepy. 

It's hard to define requirement about what should unwrap return, if there is no hash - all defined keys with `nil`? or no keys, no root? etc.

What do you think?

**Comment by Kukunin** [comment]
Issue is still relevant in cases of inline storage of value objects

```ruby
        unwrap :agent do
          attribute :agent_name, from: :name
          attribute :agent_email, from: :email
          attribute :agent_phone, from: :phone
        end
```

will crash, if `agent` is nil (which may be valid point, if agent is optional).

Currently workaround is very ugly, like overriding `#call` method and does something like

          arg[:agent] = {} if arg[:agent].nil?

**Comment by solnic** [comment]
Closing as this DSL will be deprecated
